<!-- 
<!DOCTYPE html>
<html>
<head>
    <title>Volunteers Report - {{ $campaign->name }}</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 12px; }
        .header { text-align: center; margin-bottom: 20px; }
        .header h1 { color: #333; margin-bottom: 5px; }
        .header p { color: #666; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th { background-color: #f2f2f2; text-align: left; }
        th, td { border: 1px solid #ddd; padding: 8px; }
        .badge { 
            padding: 3px 6px; 
            border-radius: 3px; 
            font-size: 11px;
            color: white;
            display: inline-block;
        }
        .approved { background-color: #28a745; }
        .pending { background-color: #ffc107; color: black; }
        .rejected { background-color: #dc3545; }
        .footer { margin-top: 20px; text-align: right; font-size: 10px; color: #999; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Volunteers Report</h1>
        <p>Campaign: {{ $campaign->name }}</p>
        <p>Generated on: {{ now()->format('M d, Y H:i') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Status</th>
                <th>Applied On</th>
            </tr>
        </thead>
        <tbody>
            @forelse($volunteers as $index => $volunteer)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td>{{ $volunteer->user->name ?? 'N/A' }}</td>
                <td>{{ $volunteer->user->email ?? 'N/A' }}</td>
                <td>{{ $volunteer->user->phone ?? 'N/A' }}</td>
                <td>
                    <span class="badge {{ $volunteer->status }}">
                        {{ ucfirst($volunteer->status) }}
                    </span>
                </td>
                <td>{{ optional($volunteer->created_at)->format('M d, Y') ?? 'N/A' }}</td>
            </tr>
            @empty
            <tr>
                <td colspan="6" style="text-align: center;">No volunteers found</td>
            </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        Page 1 of 1 • Generated by {{ config('app.name') }}
    </div>
</body>
</html> -->
<!DOCTYPE html>
<html>
<head>
    <title>Volunteers Report - {{ $campaign->name }}</title>
    <style>
        /* Basic styling for the PDF */
        body { font-family: Arial; font-size: 12px; }
        table { width: 100%; border-collapse: collapse; }
        th { background-color: #f2f2f2; }
        th, td { border: 1px solid #ddd; padding: 8px; }
    </style>
</head>
<body>
    <div style="display:flex;justify-content:center;height:80px;">
    <img src="assets/frontend/images/loader.svg" alt="Logo" ><span  style="margin:0px 1px;color :#FF6600; font-size:40px"> Newhope </span>
      </div>  
    <!-- <h1>Volunteers for: {{ $campaign->name }}</h1> -->
    <h1>Volunteers Report</h1>
        <p>Campaign: {{ $campaign->name }}</p>
        <p>Generated on: {{ now()->format('M d, Y H:i') }}</p>
    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Full Name</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Status</th>
                <th>Applied On</th>
            </tr>
        </thead>
        <tbody>
            @foreach($volunteers as $index => $volunteer)
            <tr>
                <td>{{ $index + 1 }}</td>
                <!-- Combine first + last name -->
                <td>{{ $volunteer->user->first_name }} {{ $volunteer->user->last_name }}</td>
                <td>{{ $volunteer->user->email ?? 'N/A' }}</td>
                <!-- Check both phone fields -->
                <td>{{ $volunteer->phone ?? $volunteer->user->phone ?? 'N/A' }}</td>
                <td>{{ ucfirst($volunteer->status) }}</td>
                <!-- Safe date formatting -->
                <td>{{ $volunteer->created_at->format('M d, Y') }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
</body>
</html>